apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-cert
#spec:
#  secretName: letsencrypt-cert
#  dnsNames:
#  - kibana.sequ.re
#  - monitoring.sequ.re
#  issuerRef:
#    name: letsencrypt-staging
#    kind: ClusterIssuer
spec:
  secretName: letsencrypt-cert-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - kibana.sequ.re
  - monitoring.sequ.re
