apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: monitoring
  namespace: monitoring
spec:
  version: 8.1.3
  nodeSets:
  - name: es
    count: 1
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi #100Gi
        storageClassName: sc-warm-cold
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: monitoring
  namespace: monitoring
spec:
  version: 8.1.3
  count: 1
  elasticsearchRef:
    name: monitoring
  config:
    xpack.security.authc.providers:
      basic.basic1:
        order: 0
