apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-warm-cold
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true